// Katalog produk Resmi Kartika Sari, MAMADEE & UMKM untuk Acara APTIRMIKI.

const CATEGORIES = [
  "Bolen & Pastry Kartika Sari",
  "Bolu & Kue Kartika Sari",
  "Brownies Kartika Sari",
  "Cemilan & Snack Kartika Sari",
  "Merchandise & Aksesoris Kartika Sari",
  "Minuman & Kopi MAMADEE",
  "Produk UMKM"
];

const products = [
  {
    "id": "kopi-ace-500ml",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Kopi A.C.E (Aren Creamy Espresso) 500 ml",
    "brand": "MAMADEE",
    "description": "Bold espresso berpadu sempurna dengan manisnya gula aren asli dan susu creamy yang lumer di mulut. Klasik, pas, dan anti enek! Sudah termasuk Cooler bag & ice gel.",
    "price": 45000,
    "supplierPrice": 28000,
    "unit": "botol 500ml",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "3-4 hari di kulkas | 6-8 jam di suhu ruang",
    "image": "/images/products/kopi-ace.jpg"
  },
  {
    "id": "kopi-ace-1-liter",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Kopi A.C.E (Aren Creamy Espresso) 1 Liter",
    "brand": "MAMADEE",
    "description": "Bold espresso berpadu sempurna dengan manisnya gula aren asli dan susu creamy yang lumer di mulut. Klasik, pas, dan anti enek! Sudah termasuk Cooler bag & ice gel.",
    "price": 80000,
    "supplierPrice": 60000,
    "unit": "botol 1L",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "3-4 hari di kulkas | 6-8 jam di suhu ruang",
    "image": "/images/products/kopi-ace.jpg"
  },
  {
    "id": "kopi-bce-500ml",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Kopi B.C.E (Butterscotch Creamy Espresso) 500 ml",
    "brand": "MAMADEE",
    "description": "Sensasi ngopi mewah dengan aroma butterscotch yang wangi gurih dan tekstur creamy yang langsung bikin mood naik. Sudah termasuk Cooler bag & ice gel.",
    "price": 50000,
    "supplierPrice": 35000,
    "unit": "botol 500ml",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "3-4 hari di kulkas | 6-8 jam di suhu ruang",
    "image": "/images/products/kopi-bce.png"
  },
  {
    "id": "kopi-bce-1-liter",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Kopi B.C.E (Butterscotch Creamy Espresso) 1 Liter",
    "brand": "MAMADEE",
    "description": "Sensasi ngopi mewah dengan aroma butterscotch yang wangi gurih dan tekstur creamy yang langsung bikin mood naik. Sudah termasuk Cooler bag & ice gel.",
    "price": 90000,
    "supplierPrice": 80000,
    "unit": "botol 1L",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "3-4 hari di kulkas | 6-8 jam di suhu ruang",
    "image": "/images/products/kopi-bce.png"
  },
  {
    "id": "cendol-end-to-end-500ml",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Cendol End-To-End 500 ml",
    "brand": "MAMADEE",
    "description": "Cendol kekinian berbalut susu creamy, gula aren homemade, jelly kenyal, dan wangi buah nangka. Dijamin endul sampai tetesan terakhir! Sudah termasuk Cooler bag & ice gel.",
    "price": 35000,
    "supplierPrice": 28000,
    "unit": "botol 500ml",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "",
    "image": "/images/products/cendol-end-to-end.png"
  },
  {
    "id": "cendol-end-to-end-1-liter",
    "category": "Minuman & Kopi MAMADEE",
    "name": "Cendol End-To-End 1 Liter",
    "brand": "MAMADEE",
    "description": "Cendol kekinian berbalut susu creamy, gula aren homemade, jelly kenyal, dan wangi buah nangka. Dijamin endul sampai tetesan terakhir! Sudah termasuk Cooler bag & ice gel.",
    "price": 70000,
    "supplierPrice": 55000,
    "unit": "botol 1L",
    "origin": "MAMADEE Jakarta",
    "expiryDetail": "",
    "image": "/images/products/cendol-end-to-end.png"
  },
  {
    "id": "sambal-baby-cumi",
    "category": "Produk UMKM",
    "name": "Sambal Baby Cumi - Dapur Neng Sri",
    "brand": "Dapur Neng Sri",
    "description": "Sambal baby cumi gurih nikmat dengan pedas mantap khas Dapur Neng Sri. Penyelamat segala rasa, tanpa bahan pengawet.",
    "price": 23000,
    "supplierPrice": 19500,
    "unit": "toples",
    "origin": "Dapur Neng Sri",
    "expiryDetail": "Tahan 1-2 Bulan di Kulkas",
    "image": "/images/products/sambal-baby-cumi.jpg"
  },
  {
    "id": "sambel-pecel-imah-abi",
    "category": "Produk UMKM",
    "name": "Sambel Pecel - Dapur Imah Abi (50g)",
    "brand": "Dapur Imah Abi",
    "description": "Sambel pecel khas Dapur Imah Abi dengan rasa ndeso bikin nagih! 100% bahan pilihan berkualitas, higienis & tanpa pengawet.",
    "price": 7000,
    "supplierPrice": 5000,
    "unit": "pouch 50g",
    "origin": "Dapur Imah Abi",
    "expiryDetail": "Tahan 2-3 Bulan",
    "image": "/images/products/sambel-pecel-imah-abi.jpg"
  },
  {
    "id": "pisang-bolen-keju-special-regular",
    "name": "Pisang Bolen - Keju Special - REGULAR",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 87500,
    "supplierPrice": 72500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/ut36tu56efyeag8zusf3oy_size_800_webp_Si2Qdte.webp"
  },
  {
    "id": "pisang-bolen-cokelat-keju-regular",
    "name": "Pisang Bolen - Cokelat Keju - REGULAR",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 90000,
    "supplierPrice": 75000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/s2u885wmhsgxfuslh5btaf_size_800_webp.webp"
  },
  {
    "id": "durian-keju-bolen",
    "name": "Durian Keju Bolen",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 87500,
    "supplierPrice": 72500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ngcshocfs2cjjfzpk5p5gw_size_800_webp.webp"
  },
  {
    "id": "peyeum-keju-bolen",
    "name": "Peyeum Keju Bolen",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 85000,
    "supplierPrice": 70000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/l37hm9gwajsjesitm5lyax_size_800_webp_Su1adlp.webp"
  },
  {
    "id": "pisang-bolen-isi-6-bollen-pisang-keju-coklat",
    "name": "Pisang Bolen Isi 6 - Bollen Pisang Keju Coklat",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 65000,
    "supplierPrice": 50000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/gbtpd2nlcvyk7pehwvoiyt_size_800_webp_vRaNvXQ.webp"
  },
  {
    "id": "pisang-bolen-isi-6-bollen-pisang-keju-special",
    "name": "Pisang Bolen Isi 6 - Bollen Pisang Keju Special",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 62500,
    "supplierPrice": 47500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/qqhevoeeyidjrcyfbpwzcx_size_800_webp_1v15oTf.webp"
  },
  {
    "id": "banana-crispy",
    "name": "Banana Crispy",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 90000,
    "supplierPrice": 75000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/eoqs3trsndat3smrxn7nik_size_800_webp_FKZYvAx.webp"
  },
  {
    "id": "banana-crispy-mini",
    "name": "Banana Crispy MINI",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 77500,
    "supplierPrice": 62500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/qg7qwmjwznlabwvddjxuc8_size_800_webp_NLLjOU1.webp"
  },
  {
    "id": "cheese-roll",
    "name": "CHEESE Roll",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 90000,
    "supplierPrice": 75000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/mdtzs6tgyxvbhpv7csscfa_size_800_webp_bcxgB0d.webp"
  },
  {
    "id": "choco-roll",
    "name": "Choco Roll",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 80000,
    "supplierPrice": 65000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/rc9bmwdwhdgqrktxddajxv_size_800_webp_X03AaKR.webp"
  },
  {
    "id": "cheese-stick",
    "name": "CHEESE Stick",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 90000,
    "supplierPrice": 75000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/upzn8brqmjktjmgtrxtmln_size_800_webp_Mgi1CRv.webp"
  },
  {
    "id": "choco-pastry",
    "name": "Choco Pastry",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 82500,
    "supplierPrice": 67500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/gogtqtopstmaovyvgjlf9e_size_800_webp_ycWthNc.webp"
  },
  {
    "id": "banana-roll-pandan",
    "name": "Banana Roll Pandan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 75000,
    "supplierPrice": 60000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/dzfjzlygpd2nfkhfq5oudc_size_800_webp_WScsAns.webp"
  },
  {
    "id": "lapis-legit-tikar",
    "name": "Lapis Legit Tikar",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 349000,
    "supplierPrice": 334000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/bcffabuhhgmezqhmbpspoe_size_800_webp_xkGNze6.webp"
  },
  {
    "id": "lapis-legit-prunes-roll",
    "name": "Lapis Legit Prunes Roll",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 215000,
    "supplierPrice": 200000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/cpobwzeh538akvzq9xfrcf_size_800_webp_9QNAxEN.webp"
  },
  {
    "id": "lapis-philipine-pandan",
    "name": "Lapis Philipine Pandan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 177500,
    "supplierPrice": 162500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/5/12/wc8tyy7dkjehlzhavakf42_size_800_webp.webp"
  },
  {
    "id": "lapis-philipine-coklat",
    "name": "Lapis Philipine Coklat",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 177500,
    "supplierPrice": 162500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/c3jnlw6tcgr3pytmmsgrqn_size_800_webp.webp"
  },
  {
    "id": "banana-cake-original",
    "name": "Banana Cake Original",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 100000,
    "supplierPrice": 85000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/566yghfwcxceqcuceiseuv_size_800_webp_2GcYSON.webp"
  },
  {
    "id": "banana-cake-coklat",
    "name": "Banana Cake Coklat",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 100000,
    "supplierPrice": 85000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/vnntgeu5nohossrndahgds_size_800_webp_OY3Daku.webp"
  },
  {
    "id": "chiffon-cake-ketan-hitam",
    "name": "Chiffon Cake - Ketan Hitam",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 95000,
    "supplierPrice": 80000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/jhidtqup6vnwfunkgmsejz_size_800_webp.webp"
  },
  {
    "id": "lapis-legit-roll-original",
    "name": "Lapis Legit Roll Original",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 190000,
    "supplierPrice": 175000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/5prmvrkwopk69ckbtcqwng_size_800_webp.webp"
  },
  {
    "id": "brownies-panggang-original",
    "name": "Brownies Panggang - Original",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 120000,
    "supplierPrice": 105000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/lojmb5ts8qnb6x3y4cmm3j_size_800_webp_Z6W2Cko.webp"
  },
  {
    "id": "brownies-trio",
    "name": "Brownies Trio",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ptoevcfszyzmdftmxca4zj_size_800_webp.webp"
  },
  {
    "id": "brownies-panggang-choco-chips",
    "name": "Brownies Panggang - Choco Chips",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 125000,
    "supplierPrice": 110000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/55e8hplyvwcdcvpwzxaxv2_size_800_webp_p7VKtXG.webp"
  },
  {
    "id": "brownies-panggang-special-keju",
    "name": "Brownies Panggang - Special Keju",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 135000,
    "supplierPrice": 120000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/jsruv64ktdqylerzgzatdx_size_800_webp_VrU7CCe.webp"
  },
  {
    "id": "brownies-panggang-special-mocca",
    "name": "Brownies Panggang - Special Mocca",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 125000,
    "supplierPrice": 110000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/8tjdwgrvnwt2w4a4lpeumd_size_800_webp_i3JV0xu.webp"
  },
  {
    "id": "brownies-panggang-special-tiramisu",
    "name": "Brownies Panggang - Special Tiramisu",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 135000,
    "supplierPrice": 120000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/slwuehjizsqznzweshk2cg_size_800_webp.webp"
  },
  {
    "id": "brownies-panggang-raisin",
    "name": "Brownies Panggang - Raisin",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 125000,
    "supplierPrice": 110000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/r6fwmuwc8vjka4yjbzjbwj_size_800_webp_RpVkjdT.webp"
  },
  {
    "id": "brownies-panggang-mede",
    "name": "Brownies Panggang - Mede",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 135000,
    "supplierPrice": 120000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/sclpv9fcldkn63j3rpq3pb_size_800_webp_SYERM4E.webp"
  },
  {
    "id": "brownies-gulung-coklat",
    "name": "Brownies Gulung - Coklat",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 67500,
    "supplierPrice": 52500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ygommcvxrtnshacwzvcs2p_size_800_webp_rs3CTUX.webp"
  },
  {
    "id": "brownies-gulung-kacang",
    "name": "Brownies Gulung - Kacang",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 67500,
    "supplierPrice": 52500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/hxcpscagby6mnk9ufz8rit_size_800_webp_ws3UJh8.webp"
  },
  {
    "id": "brownies-gulung-keju",
    "name": "Brownies Gulung - Keju",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 67500,
    "supplierPrice": 52500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/k9pfh5hpyhychu8iihvvm6_size_800_webp_RSqmN3P.webp"
  },
  {
    "id": "brownies-kukus-adinda",
    "name": "Brownies Kukus - Adinda",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 90000,
    "supplierPrice": 75000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/7kcdyzccj8jky4hecxgfvd_size_800_webp_ZXyDuyB.webp"
  },
  {
    "id": "brownies-kukus-pandan",
    "name": "Brownies Kukus - Pandan",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 95000,
    "supplierPrice": 80000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/sq8yqf7jhmsrsiyeaffx2r_size_800_webp_lcSxp7J.webp"
  },
  {
    "id": "brownies-kukus-keju",
    "name": "Brownies Kukus - Keju",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 92500,
    "supplierPrice": 77500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ewkrt5bnqvuhi5rebgrf9a_size_800_webp_1UsDDSJ.webp"
  },
  {
    "id": "brownies-kukus-marble",
    "name": "Brownies Kukus - Marble",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 92500,
    "supplierPrice": 77500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/3c3vjxyd6hkwphaqczb3ys_size_800_webp_Qpbbsl9.webp"
  },
  {
    "id": "brownies-kukus-tiramisu",
    "name": "Brownies Kukus - Tiramisu",
    "brand": "Kartika Sari",
    "category": "Brownies Kartika Sari",
    "price": 92500,
    "supplierPrice": 77500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "7-10 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/6ezxwgzjlxqwtkycri9sfw_size_800_webp_q7npxfr.webp"
  },
  {
    "id": "bagelen-butter",
    "name": "Bagelen Butter",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 85000,
    "supplierPrice": 70000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/k5rdxkgwhwnuqky6jkv7yc_size_800_webp_0vobPTd.webp"
  },
  {
    "id": "bagelen-almond",
    "name": "Bagelen ALMOND",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 87000,
    "supplierPrice": 72000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/kgdhb8bwmeggtyw66ejtua_size_800_webp_fJpeLb2.webp"
  },
  {
    "id": "bagelen-cheese",
    "name": "Bagelen CHEESE",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 87000,
    "supplierPrice": 72000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/zvknecebedh3uwzzaozxv4_size_800_webp_gy6cjZf.webp"
  },
  {
    "id": "bagelen-mocha",
    "name": "Bagelen Mocha",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 85000,
    "supplierPrice": 70000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/ngantdyuznta7rudittccz_size_800_webp_FzPP3WY.webp"
  },
  {
    "id": "bagelen-assorted-flavors-155-gram",
    "name": "Bagelen Assorted Flavors 155 Gram",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 89000,
    "supplierPrice": 74000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/cyyturhhhpz9af9qoaaxfc_size_800_webp_lESfwRL.webp"
  },
  {
    "id": "toast-bread-chocolate-201-2-gram",
    "name": "Toast Bread Chocolate 201.2 Gram",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 73000,
    "supplierPrice": 58000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/1/15/6c4midv8uowaxryh5opy9u_size_800_webp_PBuB3VQ.webp"
  },
  {
    "id": "toast-bread-butter-142-4-gram",
    "name": "Toast Bread Butter 142.4 Gram",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 63000,
    "supplierPrice": 48000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/1/15/g7ozmx9wknf9cq2mtg6yqi_size_800_webp_LQSbQhK.webp"
  },
  {
    "id": "soes-cream-chocolate-hazel-tin",
    "name": "Soes Cream Chocolate Hazel Tin",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 75000,
    "supplierPrice": 60000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/bghv9w87ee7lyj2mnkdbiv_size_800_webp_IH6eFSw.webp"
  },
  {
    "id": "soes-cream-yogurt-strawberry-can",
    "name": "Soes Cream Yogurt Strawberry Can",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 60000,
    "supplierPrice": 45000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/tftcaoymuvpltkixuxxrih_size_800_webp_b0QO8kG.webp"
  },
  {
    "id": "soes-cream-cheese-tin",
    "name": "Soes Cream CHEESE Tin",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 60000,
    "supplierPrice": 45000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/ghfzpxnfjdrnmtsep4p6tu_size_800_webp.webp"
  },
  {
    "id": "soes-cream-cokelat-hazel-pouch",
    "name": "Soes Cream Cokelat Hazel Pouch",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 53000,
    "supplierPrice": 38000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/djxppmxmsfaw7p9ku4hl5h_size_800_webp_Ru6KXsa.webp"
  },
  {
    "id": "soes-cream-yogurt-strawberry-pouch",
    "name": "Soes Cream Yogurt Strawberry Pouch",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 43000,
    "supplierPrice": 28000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/bxmmkldfrcev5gp4h6ih9a_size_800_webp.webp"
  },
  {
    "id": "soes-cream-cheese-pouch",
    "name": "Soes Cream CHEESE Pouch",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 43000,
    "supplierPrice": 28000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/7vdduwstfouuqbi357hbxf_size_800_webp.webp"
  },
  {
    "id": "soes-kering-keju",
    "name": "Soes Kering Keju",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 63000,
    "supplierPrice": 48000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/hbng5jvbhuvmgssgfpef8k_size_800_webp_63ua14s.webp"
  },
  {
    "id": "almond-cookies-120-4-gram",
    "name": "ALMOND Cookies 120,4 Gram",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 75000,
    "supplierPrice": 60000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/vnyxxmvfdy9zwnijp2kymv_size_800_webp_IH4D9WC.webp"
  },
  {
    "id": "crispy-toast-vanilla-tabung",
    "name": "Crispy Toast Vanilla Tabung",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 63000,
    "supplierPrice": 48000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/nrbnhtsfvottjuj9bk6heq_size_800_webp_o65kGxb.webp"
  },
  {
    "id": "choco-stick",
    "name": "Choco Stick",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 80000,
    "supplierPrice": 65000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/dk7cat6pgvclc78bnctsjh_size_800_webp_MXx6JRe.webp"
  },
  {
    "id": "wafer-coklat-kartika-sari",
    "name": "Wafer Coklat Kartika Sari",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 95000,
    "supplierPrice": 80000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/1/15/c5sbwurjltwqxnajf9bfkz_size_800_webp_Li654YF.webp"
  },
  {
    "id": "naastart-keju-cookies",
    "name": "Naastart Keju Cookies",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 190500,
    "supplierPrice": 175500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/t8vqfmzbab79atf8s3wa7y_size_800_webp_a8KDy4V.webp"
  },
  {
    "id": "naastart-cookies",
    "name": "Naastart Cookies",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 210000,
    "supplierPrice": 195000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/b9kyaafuj2cbdfj4cjvahb_size_800_webp_6EmPiOI.webp"
  },
  {
    "id": "kaastengels-cookies",
    "name": "Kaastengels Cookies",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 205000,
    "supplierPrice": 190000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/rx6mzbsxnyp5w6lubxfqdc_size_800_webp_UOfftYH.webp"
  },
  {
    "id": "lidah-kucing",
    "name": "Lidah Kucing",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 175000,
    "supplierPrice": 160000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/wialrjyvt2wrrdeaqaxyrw_size_800_webp_SjRtf2L.webp"
  },
  {
    "id": "almond-cookies",
    "name": "ALMOND Cookies",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 200000,
    "supplierPrice": 185000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/6gvwlbipytx3ab5sukchwy_size_800_webp_p6hfxau.webp"
  },
  {
    "id": "kaastengel-kotak-10x10",
    "name": "Kaastengel Kotak 10x10",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 155000,
    "supplierPrice": 140000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/rhbr8ahtrws847bnb7aawh_size_800_webp_ndcPFIn.webp"
  },
  {
    "id": "naastart-original-10x10",
    "name": "Naastart Original 10x10",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 155000,
    "supplierPrice": 140000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/jvu8tbxewqtkkirue2dkfk_size_800_webp_Lxe3iRQ.webp"
  },
  {
    "id": "kartika-sari-hampers-can",
    "name": "Kartika Sari Hampers Can",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 155000,
    "supplierPrice": 140000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/1/15/lgr5en9ncg2z32kdawazyl_size_800_webp_MBarekd.webp"
  },
  {
    "id": "kartika-sari-hampers-3s",
    "name": "Kartika Sari Hampers 3s",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 195000,
    "supplierPrice": 180000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/8/10/e4doljtijcdvoghggzmayb_size_800_webp.webp"
  },
  {
    "id": "kartika-sari-hampers-4s",
    "name": "Kartika Sari Hampers 4s",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 255000,
    "supplierPrice": 240000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/8/10/j6uyqdt4b4gcmsdhaucgtk_size_800_webp.webp"
  },
  {
    "id": "kartika-sari-hampers-5s",
    "name": "Kartika Sari Hampers 5s",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 305000,
    "supplierPrice": 290000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/8/10/d98ty3naoaciukrfrtbuur_size_800_webp.webp"
  },
  {
    "id": "bandrek-bandung-braga-regular",
    "name": "Bandrek Bandung Braga REGULAR",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 49000,
    "supplierPrice": 34000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/vr3d6pefblq8lbvlsvtt7z_size_800_webp_olgoF59.webp"
  },
  {
    "id": "bandrek-bandung-braga-extra-hot",
    "name": "Bandrek Bandung Braga Extra Hot",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 52000,
    "supplierPrice": 37000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/7djbtu33kgmwny4konrrr5_size_800_webp_hqAv9BD.webp"
  },
  {
    "id": "seblak-instan-sehati",
    "name": "Seblak Instan Sehati",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 30000,
    "supplierPrice": 15000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/gnrqv9encm3hjvfjtrfzmh_size_800_webp_E9GX6RI.webp"
  },
  {
    "id": "cuanki-express",
    "name": "Cuanki Express",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 41000,
    "supplierPrice": 26000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/eycxrxlq3uguneqownv7xk_size_800_webp.webp"
  },
  {
    "id": "mie-seblak-geprek-sami-raos",
    "name": "Mie Seblak Geprek Sami Raos",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 50000,
    "supplierPrice": 35000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ac9joyazcqqpqzgmk9fdtb_size_800_webp_KhJp9tU.webp"
  },
  {
    "id": "dodol-wijen-bestory",
    "name": "Dodol Wijen Bestory",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 38000,
    "supplierPrice": 23000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/gm6uf7ds44dxhnqtfjeo5t_size_800_webp.webp"
  },
  {
    "id": "dodol-susu-spc-tk",
    "name": "Dodol Susu Spc Tk",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 46000,
    "supplierPrice": 31000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/uzbbhptn5t6gcvthh7xyh9_size_800_webp.webp"
  },
  {
    "id": "dodol-picnic-sp",
    "name": "Dodol Picnic SP",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 63000,
    "supplierPrice": 48000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/hz5tkracchdtfom5qr6exn_size_800_webp.webp"
  },
  {
    "id": "telur-gabus-keju-tabung",
    "name": "Telur Gabus Keju Tabung",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 92000,
    "supplierPrice": 77000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/2bcpgtehqtbolrvgdxvbsc_size_800_webp_2SDBRzN.webp"
  },
  {
    "id": "telur-gabus-keju-tdy",
    "name": "Telur Gabus Keju Tdy",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 54000,
    "supplierPrice": 39000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/9h9rcmqpgonnlz85ndkqpk_size_800_webp_0yS590R.webp"
  },
  {
    "id": "telur-gabus-aaa",
    "name": "Telur Gabus Aaa",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 86000,
    "supplierPrice": 71000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/ykhhdn7mcvsxu7ys4xzfsr_size_800_webp.webp"
  },
  {
    "id": "seblak-koin",
    "name": "Seblak Koin",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 38000,
    "supplierPrice": 23000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/bgbkehpmzbnjm8abyhva99_size_800_webp_zPgjIQo.webp"
  },
  {
    "id": "stick-kentang-net",
    "name": "Stick Kentang Net",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 33500,
    "supplierPrice": 18500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/4wpauclxnqorjf8heoralr_size_800_webp.webp"
  },
  {
    "id": "keripik-cimpring-bawang-original",
    "name": "Keripik Cimpring Bawang Original",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 44000,
    "supplierPrice": 29000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ftpn3hw4aekbl5igfsqihm_size_800_webp_LffiPIs.webp"
  },
  {
    "id": "kerupuk-jaat",
    "name": "Kerupuk Jaat",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 38000,
    "supplierPrice": 23000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/dhmhlsvxszv5mdvwtspcdz_size_800_webp_HUcCwt7.webp"
  },
  {
    "id": "kerupuk-paru-ss",
    "name": "Kerupuk Paru SS",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 89000,
    "supplierPrice": 74000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ncm2pprdh7rrndgshbsupn_size_800_webp.webp"
  },
  {
    "id": "kerupuk-sumpia-udang-ss",
    "name": "Kerupuk Sumpia Udang SS",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 51000,
    "supplierPrice": 36000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/7ecnrudsejx2tpbewhjpuq_size_800_webp_LxVbvRn.webp"
  },
  {
    "id": "keripik-belut-indorasa",
    "name": "Keripik Belut Indorasa",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 66000,
    "supplierPrice": 51000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/bzbtphbuksh6trubx3jgys_size_800_webp.webp"
  },
  {
    "id": "kentang-putih-cap-jempol",
    "name": "Kentang Putih Cap Jempol",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 92000,
    "supplierPrice": 77000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/wyhgclmhtktoyabb6y6kuu_size_800_webp.webp"
  },
  {
    "id": "kentang-putih-b-ss",
    "name": "Kentang Putih B SS",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 84000,
    "supplierPrice": 69000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/dqh3kotpdjjabecoyk9pfj_size_800_webp.webp"
  },
  {
    "id": "kentang-putih-sari-rasa",
    "name": "Kentang Putih Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 92000,
    "supplierPrice": 77000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/irywfagqfzs6wdr22vihng_size_800_webp_8FFXQ8d.webp"
  },
  {
    "id": "kerupuk-basreng-vs",
    "name": "Kerupuk Basreng Vs",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 49000,
    "supplierPrice": 34000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/h2gdfwyausc883x9hbvxma_size_800_webp.webp"
  },
  {
    "id": "kerupuk-basreng-original-sari-rasa",
    "name": "Kerupuk Basreng Original - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 56000,
    "supplierPrice": 41000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/3npc2xj4xsp32p9f3fyo6z_size_800_webp_cljsiG6.webp"
  },
  {
    "id": "kerupuk-basreng-pedas-sari-rasa",
    "name": "Kerupuk Basreng Pedas - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 59000,
    "supplierPrice": 44000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/hitp6cvrs4gqwkomwfsuy3_size_800_webp.webp"
  },
  {
    "id": "tempe-kotak-ss",
    "name": "Tempe Kotak SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 74000,
    "supplierPrice": 59000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/dyuxex3twgijcm8jnvzp9s_size_800_webp_D3hOwfb.webp"
  },
  {
    "id": "keripik-tempe-original-bulat-sari-rasa",
    "name": "Keripik Tempe Original Bulat - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 59000,
    "supplierPrice": 44000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ebguuw6xmzwbpftv668gue_size_800_webp_pZQHHOE.webp"
  },
  {
    "id": "keripik-tempe-mentega-sari-rasa",
    "name": "Keripik Tempe Mentega - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 55000,
    "supplierPrice": 40000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/94jv33xptjpkgf3qnuawi5_size_800_webp_daSIYGn.webp"
  },
  {
    "id": "keripik-tempe-pedas-manis-sari-rasa",
    "name": "Keripik Tempe Pedas Manis - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 59000,
    "supplierPrice": 44000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/uj9vrfy2keabwn9hi6d7sk_size_800_webp_xtjN426.webp"
  },
  {
    "id": "keripik-tempe-original-kotak-sari-rasa",
    "name": "Keripik Tempe Original Kotak - Sari Rasa",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 59000,
    "supplierPrice": 44000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/mjcbmiwtyoxpbrc8pz6ua6_size_800_webp_mCFEjG9.webp"
  },
  {
    "id": "tempe-sagu-ss",
    "name": "Tempe Sagu SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 64000,
    "supplierPrice": 49000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/7owbrpicesjxwa9us2txfe_size_800_webp_tdakrqY.webp"
  },
  {
    "id": "sale-pisang-crispy-vs",
    "name": "Sale Pisang Crispy Vs",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 52000,
    "supplierPrice": 37000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/be3x3z7j4wwena7gyzwzm6_size_800_webp_Zji534t.webp"
  },
  {
    "id": "sale-pisang-jari-yy",
    "name": "Sale Pisang Jari Yy",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 57000,
    "supplierPrice": 42000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/bp9whgclgtvq7yv3gme4zw_size_800_webp.webp"
  },
  {
    "id": "sale-pisang-lidah-yy",
    "name": "Sale Pisang Lidah Yy",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 42000,
    "supplierPrice": 27000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/d7slpmlaage8x3ngflwhwr_size_800_webp_AhCAq9j.webp"
  },
  {
    "id": "sale-pisang-suka-senang",
    "name": "Sale Pisang Suka Senang",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 44000,
    "supplierPrice": 29000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/hpayckvguqzpaednsywrwt_size_800_webp.webp"
  },
  {
    "id": "sale-pisang-keju-ss",
    "name": "Sale Pisang Keju SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 62000,
    "supplierPrice": 47000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/ewq7nefld44tohh4e3hdhx_size_800_webp_kf4L1jM.webp"
  },
  {
    "id": "plush-keychain-bollen",
    "name": "Plush Keychain Bollen",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/pplapyqutfnfoaphf5mxta_size_800_webp_ejwDjRt.webp"
  },
  {
    "id": "plush-keychain-roll-tart",
    "name": "Plush Keychain Roll Tart",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/35vemkb3r6wfh2scfwgb6r_size_800_webp_cTFUElP.webp"
  },
  {
    "id": "plush-keychain-bolu-kukus",
    "name": "Plush Keychain Bolu Kukus",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/frhdj9ogexbgaw5cowojh4_size_800_webp_S3K0jR8.webp"
  },
  {
    "id": "plush-keychain-banana-roll",
    "name": "Plush Keychain Banana Roll",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/zb7hcpsfvj93x3pd2ivkba_size_800_webp_GByaLx3.webp"
  },
  {
    "id": "plush-keychain-saucijz-brood",
    "name": "Plush Keychain Saucijz Brood",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/9ekm7xx7awizphsonk59mt_size_800_webp_ertoeeo.webp"
  },
  {
    "id": "keychain-akrilik-bollen-kartikasari-x-ayang-cempaka",
    "name": "Keychain Akrilik Bollen [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 40000,
    "supplierPrice": 25000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/gqnab4yqexdvexqeeoqjzj_size_800_webp.webp"
  },
  {
    "id": "keychain-akrilik-lemper-kartikasari-x-ayang-cempaka",
    "name": "Keychain Akrilik Lemper [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 40000,
    "supplierPrice": 25000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/euiyx4rjkqnkue8rrvxagi_size_800_webp.webp"
  },
  {
    "id": "keychain-akrilik-roll-tart-kartikasari-x-ayang-cempaka",
    "name": "Keychain Akrilik Roll Tart [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 40000,
    "supplierPrice": 25000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/utmudemcj48wkfrvul66ee_size_800_webp.webp"
  },
  {
    "id": "keychain-akrilik-bolu-kukus-kartikasari-x-ayang-cempaka",
    "name": "Keychain Akrilik Bolu Kukus [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 40000,
    "supplierPrice": 25000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/5gyeloeafcd8ytswrwrxy4_size_800_webp.webp"
  },
  {
    "id": "keychain-akrilik-banana-roll-kartikasari-x-ayang-cempaka",
    "name": "Keychain Akrilik Banana Roll [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 40000,
    "supplierPrice": 25000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/vquw9caojdfroer6nttv6u_size_800_webp.webp"
  },
  {
    "id": "cheese-bites-90-gram",
    "name": "CHEESE Bites 90 Gram",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 75000,
    "supplierPrice": 60000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/4/7/k2opygdosavd3m6oxc4vdx_size_800_webp.webp"
  },
  {
    "id": "tumbler-genz-putih-kartikasari-x-ayang-cempaka",
    "name": "Tumbler Genz Putih [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 225000,
    "supplierPrice": 210000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/ockt43zecqw3i9uxq9zxte_size_800_webp_GRefHQI.webp"
  },
  {
    "id": "tumbler-genz-merah-kartikasari-x-ayang-cempaka",
    "name": "Tumbler Genz Merah [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 225000,
    "supplierPrice": 210000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/jez7dhz6p3nc8jnchdfg8r_size_800_webp_Kz4XXwu.webp"
  },
  {
    "id": "tumbler-gelas-kartikasari-x-ayang-cempaka",
    "name": "Tumbler Gelas [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 225000,
    "supplierPrice": 210000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/pusnllxwtcgdaf5sdizzxu_size_800_webp_gm3Wfzq.webp"
  },
  {
    "id": "tumbler-cork-kartikasari-x-ayang-cempaka",
    "name": "Tumbler Cork [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 265000,
    "supplierPrice": 250000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/6/fhzw5kzevm8mywc9d2nc8p_size_800_webp_IrwSJdo.webp"
  },
  {
    "id": "t-shirt-ayang-bollen-kartikasari-x-ayang-cempaka",
    "name": "T-Shirt Ayang Bollen [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 210000,
    "supplierPrice": 195000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/ysvdsj4me3pwqrcnaqzbh9_size_800_webp.webp"
  },
  {
    "id": "t-shirt-ayang-ks-delight-kartikasari-x-ayang-cempaka",
    "name": "T-Shirt Ayang KS Delight [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 210000,
    "supplierPrice": 195000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/herbyqyfsh8ayycltfhwpk_size_800_webp.webp"
  },
  {
    "id": "t-shirt-ayang-bandung-map-kartikasari-x-ayang-cempaka",
    "name": "T-Shirt Ayang Bandung Map [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 210000,
    "supplierPrice": 195000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/t9woxpffdyuflb8eyrjxpp_size_800_webp.webp"
  },
  {
    "id": "t-shirt-ayang-my-love-language-kartikasari-x-ayang-cempaka",
    "name": "T-Shirt Ayang My Love Language [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 210000,
    "supplierPrice": 195000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/cawdftvdj4cabepfhuzvmp_size_800_webp.webp"
  },
  {
    "id": "canvas-bag-bandung-map-kartikasari-x-ayang-cempaka",
    "name": "Canvas Bag Bandung Map [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 225000,
    "supplierPrice": 210000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/cbmayhq26abek3zzgzmcc9_size_800_webp_JwzZTKg.webp"
  },
  {
    "id": "canvas-bag-ks-delight-kartikasari-x-ayang-cempaka",
    "name": "Canvas Bag KS Delight [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 195000,
    "supplierPrice": 180000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/d2lldwkhjl7fixw9ebyusy_size_800_webp_Nb1ztpG.webp"
  },
  {
    "id": "foldable-bag-ks-delight-bolu-kukus-kartikasari-x-ayang-cempaka",
    "name": "Foldable Bag KS Delight Bolu Kukus [kartikasari X Ayang Cempaka]",
    "brand": "Kartika Sari",
    "category": "Merchandise & Aksesoris Kartika Sari",
    "price": 130000,
    "supplierPrice": 115000,
    "unit": "pcs",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "Awet & Tahan Lama",
    "description": "Merchandise & aksesoris resmi edisi spesial dari Kartika Sari Bandung. Desain eksklusif dan berkualitas tinggi.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/2/7/gnubi7js9xerb7etvxc7dn_size_800_webp_zhvHRud.webp"
  },
  {
    "id": "bundling-1-kemerdekaan",
    "name": "Bundling 1 Kemerdekaan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 185845,
    "supplierPrice": 170845,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/7/31/mtcgjddjofydvpyrqb2pgs_size_800_webp.webp"
  },
  {
    "id": "bundling-2-kemerdekaan",
    "name": "Bundling 2 Kemerdekaan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 185845,
    "supplierPrice": 170845,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/7/31/jdnmfnm4tuatwi88j69dvb_size_800_webp.webp"
  },
  {
    "id": "bundling-3-kemerdekaan",
    "name": "Bundling 3 Kemerdekaan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 185845,
    "supplierPrice": 170845,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/7/31/5zurcfzhphbpnqr57vjilx_size_800_webp.webp"
  },
  {
    "id": "bundling-4-kemerdekaan",
    "name": "Bundling 4 Kemerdekaan",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 185845,
    "supplierPrice": 170845,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2026/7/31/3ztagzop9qsz7xxdyf5zrr_size_800_webp.webp"
  },
  {
    "id": "pisang-bolen-keju-special-besar",
    "name": "Pisang Bolen - Keju Special - Besar",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 105000,
    "supplierPrice": 90000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/8sueedf2h75dhdrp4grgby_size_800_webp_V8Nz1Nq.webp"
  },
  {
    "id": "pisang-bolen-cokelat-keju-besar",
    "name": "Pisang Bolen - Cokelat Keju - Besar",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 107500,
    "supplierPrice": 92500,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "3-4 Hari di suhu ruang | 7 Hari di kulkas",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/4zgewmdoveqzjffennsn8f_size_800_webp_nvprxkE.webp"
  },
  {
    "id": "banana-roll-keju",
    "name": "Banana Roll Keju",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 75000,
    "supplierPrice": 60000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/btshemkiebpw9ucqmkuvvc_size_800_webp_A3eUQtX.webp"
  },
  {
    "id": "proll-tape-1-3-ly",
    "name": "Proll Tape 1/3 Ly",
    "brand": "Kartika Sari",
    "category": "Bolu & Kue Kartika Sari",
    "price": 85000,
    "supplierPrice": 70000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/4/iktgjcpoytwysi2a8rc2ec_size_800_webp_tpYyCbK.webp"
  },
  {
    "id": "pie-susu-keju",
    "name": "Pie Susu Keju",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 65000,
    "supplierPrice": 50000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/8epeviiducmcteqfnjn8ae_size_800_webp_xJ61b8F.webp"
  },
  {
    "id": "pie-susu-strawberry-chocolate",
    "name": "Pie Susu Strawberry Chocolate",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 65000,
    "supplierPrice": 50000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/ht4idxwp7p5tglexuwrgxh_size_800_webp_HjbDF62.webp"
  },
  {
    "id": "pie-susu-tiramisu",
    "name": "Pie Susu Tiramisu",
    "brand": "Kartika Sari",
    "category": "Bolen & Pastry Kartika Sari",
    "price": 65000,
    "supplierPrice": 50000,
    "unit": "box",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "4-5 Hari di suhu ruang",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/p9685pq9v2j8y6xzqjqpmx_size_800_webp_9i5bb78.webp"
  },
  {
    "id": "tempe-kotak-manis-pedas-ss",
    "name": "Tempe Kotak Manis Pedas SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 68000,
    "supplierPrice": 53000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/fk2juzwjsqauhy6wel8w7q_size_800_webp.webp"
  },
  {
    "id": "sale-pisang-lidah-ss",
    "name": "Sale Pisang Lidah SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 50000,
    "supplierPrice": 35000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/5nxjuhtsxbds7ikedrdzqc_size_800_webp_8RC2RBb.webp"
  },
  {
    "id": "sale-pisang-lidah-super-ss",
    "name": "Sale Pisang Lidah Super SS",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 53000,
    "supplierPrice": 38000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/x5rqskzkrdlph3ewwfmsba_size_800_webp.webp"
  },
  {
    "id": "keripik-pisang-madu",
    "name": "Keripik Pisang Madu",
    "brand": "Kartika Sari",
    "category": "Cemilan & Snack Kartika Sari",
    "price": 51000,
    "supplierPrice": 36000,
    "unit": "pack",
    "origin": "Kartika Sari Bandung",
    "expiryDetail": "1-2 Bulan (Kering/Snack)",
    "description": "Produk oleh-oleh asli dan legendaris dari Kartika Sari Bandung. Dibuat dengan bahan premium pilihan serta cita rasa khas yang terjamin kelezatan dan keasliannya.",
    "image": "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/ekqfepasozmxdxwfa9xszq_size_800_webp_Eecwok5.webp"
  }
];

module.exports = { products, CATEGORIES };
