// Katalog produk Oleh-Oleh Khas Jakarta untuk Acara APTIRMIKI.
// Tambah/ubah produk cukup dengan mengedit array ini (tidak perlu ubah kode lain).
// "image" dapat menggunakan URL Foto langsung atau Link Share Google Drive.

const CATEGORIES = [
  "Makanan & Minuman Khas",
  "Totebag",
  "Notes / Alat Tulis",
  "Tumbler",
  "Cangkir Enamel",
];

const products = [
  // ===== Makanan & Minuman Khas =====
  {
    id: "dodol-betawi",
    category: "Makanan & Minuman Khas",
    name: "Dodol Betawi",
    description: "Dodol legit khas Betawi, dimasak tradisional dengan gula merah.",
    price: 35000,
    supplierPrice: 25000,
    unit: "pack",
    origin: "Betawi, Jakarta",
    expiryDetail: "6 Bulan (Tanpa Pengawet)",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "biji-ketapang",
    category: "Makanan & Minuman Khas",
    name: "Biji Ketapang",
    description: "Camilan renyah gurih manis, bentuk khas biji ketapang.",
    price: 30000,
    supplierPrice: 20000,
    unit: "pack",
    origin: "Jakarta Timur",
    expiryDetail: "3 Bulan",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "akar-kelapa",
    category: "Makanan & Minuman Khas",
    name: "Akar Kelapa",
    description: "Kue kering renyah berbentuk anyaman menyerupai akar kelapa.",
    price: 30000,
    supplierPrice: 20000,
    unit: "pack",
    origin: "Betawi Asli",
    expiryDetail: "3 Bulan",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "kembang-goyang",
    category: "Makanan & Minuman Khas",
    name: "Kembang Goyang",
    description: "Kue kering renyah berbentuk bunga, digoreng dengan cetakan goyang.",
    price: 35000,
    supplierPrice: 24000,
    unit: "pack",
    origin: "Jakarta Selatan",
    expiryDetail: "2 Bulan",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "semprong",
    category: "Makanan & Minuman Khas",
    name: "Semprong",
    description: "Kue gulung tipis renyah dengan aroma kayu manis.",
    price: 32000,
    supplierPrice: 22000,
    unit: "pack",
    origin: "Jakarta Barat",
    expiryDetail: "4 Bulan",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "geplak",
    category: "Makanan & Minuman Khas",
    name: "Geplak",
    description: "Kue tradisional berbahan kelapa parut dan gula, warna-warni.",
    price: 28000,
    supplierPrice: 18000,
    unit: "pack",
    origin: "Betawi, Jakarta",
    expiryDetail: "1 Bulan",
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "bir-pletok",
    category: "Makanan & Minuman Khas",
    name: "Bir Pletok",
    description: "Minuman tradisional Betawi rempah hangat, tanpa alkohol.",
    price: 25000,
    supplierPrice: 16000,
    unit: "botol",
    origin: "Jakarta Pusat",
    expiryDetail: "6 Bulan",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "kue-satu",
    category: "Makanan & Minuman Khas",
    name: "Kue Satu",
    description: "Kue kering dari kacang hijau, lumer dan manis legit.",
    price: 30000,
    supplierPrice: 20000,
    unit: "pack",
    origin: "Jakarta Utara",
    expiryDetail: "3 Bulan",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "kue-gambang",
    category: "Makanan & Minuman Khas",
    name: "Kue Gambang",
    description: "Kue bolu khas Betawi dengan rempah kayu manis dan gula merah.",
    price: 33000,
    supplierPrice: 22000,
    unit: "pack",
    origin: "Betawi Asli",
    expiryDetail: "14 Hari",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=600&fit=crop&auto=format&q=80",
  },

  // ===== Totebag =====
  {
    id: "totebag-aptirmiki",
    category: "Totebag",
    name: "Totebag APTIRMIKI",
    description: "Totebag kanvas eksklusif dengan desain khas acara APTIRMIKI.",
    price: 45000,
    supplierPrice: 30000,
    unit: "pcs",
    origin: "Official Merch",
    expiryDetail: "Tahan Lama",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop&auto=format&q=80",
  },

  // ===== Notes / Alat Tulis =====
  {
    id: "notes-aptirmiki",
    category: "Notes / Alat Tulis",
    name: "Notes & Alat Tulis APTIRMIKI",
    description: "Set buku catatan dan pulpen dengan branding APTIRMIKI.",
    price: 20000,
    supplierPrice: 12000,
    unit: "set",
    origin: "Official Merch",
    expiryDetail: "Tahan Lama",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop&auto=format&q=80",
  },

  // ===== Tumbler =====
  {
    id: "tumbler-kayu",
    category: "Tumbler",
    name: "Tumbler Kayu",
    description: "Tumbler dengan balutan motif kayu, elegan dan ramah lingkungan.",
    price: 85000,
    supplierPrice: 60000,
    unit: "pcs",
    origin: "Official Merch",
    expiryDetail: "Tahan Lama",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&auto=format&q=80",
  },
  {
    id: "tumbler-besi",
    category: "Tumbler",
    name: "Tumbler Besi",
    description: "Tumbler stainless steel, tahan panas & dingin, kuat dan tahan lama.",
    price: 75000,
    supplierPrice: 50000,
    unit: "pcs",
    origin: "Official Merch",
    expiryDetail: "Tahan Lama",
    image: "https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=600&h=600&fit=crop&auto=format&q=80",
  },

  // ===== Cangkir Enamel =====
  {
    id: "cangkir-enamel",
    category: "Cangkir Enamel",
    name: "Cangkir Enamel",
    description: "Cangkir enamel retro dengan desain khas APTIRMIKI, unik dan kolektibel.",
    price: 40000,
    supplierPrice: 25000,
    unit: "pcs",
    origin: "Official Merch",
    expiryDetail: "Tahan Lama",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=600&fit=crop&auto=format&q=80",
  },
];

module.exports = { products, CATEGORIES };
