// Katalog produk Resmi Kartika Sari untuk Acara APTIRMIKI.

const CATEGORIES = [
  "Bolen & Pastry Kartika Sari",
  "Bolu & Kue Kartika Sari",
  "Brownies Kartika Sari",
];

const products = [
  // ===== Produk Kartika Sari =====
  {
    id: "banana-roll-pandan",
    category: "Bolu & Kue Kartika Sari",
    name: "Banana Roll Pandan (Bolu Gulung)",
    brand: "Kartika Sari",
    description: "Bolu gulung aroma pandan lembut berisikan pisang pilihan khas Kartika Sari.",
    price: 70000,
    supplierPrice: 65000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "4-5 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/dzfjzlygpd2nfkhfq5oudc_size_800_webp_WScsAns.webp",
  },
  {
    id: "lapis-legit-roll-original",
    category: "Bolu & Kue Kartika Sari",
    name: "Lapis Legit Roll Original",
    brand: "Kartika Sari",
    description: "Bolu gulung lapis legit original dengan resep legendaris khas Kartika Sari.",
    price: 175000,
    supplierPrice: 135000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "7 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/9/5prmvrkwopk69ckbtcqwng_size_800_webp.webp",
  },
  {
    id: "lapis-philipine-coklat",
    category: "Bolu & Kue Kartika Sari",
    name: "Lapis Philipine Coklat",
    brand: "Kartika Sari",
    description: "Kue lapis coklat lembut dengan cita rasa khas dan manis pas.",
    price: 162500,
    supplierPrice: 125000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "7 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/c3jnlw6tcgr3pytmmsgrqn_size_800_webp.webp",
  },
  {
    id: "pisang-bolen-keju-special",
    category: "Bolen & Pastry Kartika Sari",
    name: "Pisang Bolen - Keju Special",
    brand: "Kartika Sari",
    description: "Pisang bolen keju spesial khas Kartika Sari Bandung yang terkenal renyah dan gurih.",
    price: 72500,
    supplierPrice: 55000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "4 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/8/ut36tu56efyeag8zusf3oy_size_800_webp_Si2Qdte.webp",
  },
  {
    id: "pisang-bolen-cokelat-keju",
    category: "Bolen & Pastry Kartika Sari",
    name: "Pisang Bolen - Cokelat Keju",
    brand: "Kartika Sari",
    description: "Pisang bolen dengan kombinasi lelehan cokelat premium dan keju melimpah.",
    price: 75000,
    supplierPrice: 58000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "4 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/s2u885wmhsgxfuslh5btaf_size_800_webp.webp",
  },
  {
    id: "brownies-panggang-keju",
    category: "Brownies Kartika Sari",
    name: "Brownies Panggang - Special Keju",
    brand: "Kartika Sari",
    description: "Brownies panggang dengan taburan keju melimpah dan rasa coklat yang kaya.",
    price: 120000,
    supplierPrice: 92000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "7-10 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/jsruv64ktdqylerzgzatdx_size_800_webp_VrU7CCe.webp",
  },
  {
    id: "brownies-panggang-choco-chips",
    category: "Brownies Kartika Sari",
    name: "Brownies Panggang - Choco Chips",
    brand: "Kartika Sari",
    description: "Brownies panggang lezat ditaburi choco chips renyah manis.",
    price: 110000,
    supplierPrice: 85000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "7-10 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/55e8hplyvwcdcvpwzxaxv2_size_800_webp_p7VKtXG.webp",
  },
  {
    id: "brownies-panggang-original",
    category: "Brownies Kartika Sari",
    name: "Brownies Panggang - Original",
    brand: "Kartika Sari",
    description: "Brownies panggang rasa coklat original legit khas Kartika Sari.",
    price: 105000,
    supplierPrice: 80000,
    unit: "box",
    origin: "Kartika Sari Bandung",
    expiryDetail: "7-10 Hari",
    image: "https://omni-kartikasari.stamps.id/media/thumb/product_photo/2025/12/3/lojmb5ts8qnb6x3y4cmm3j_size_800_webp_Z6W2Cko.webp",
  },
];

module.exports = { products, CATEGORIES };
